name: Build and Release Windows

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.6'
        platform: 'windows'

    - name: Build
      run: go build -v -o out/tent.exe .